"""Draw the mod's simple pixel icons: the moodles fed by DanTraits_Moodles.lua
(all but Spoons, whose art was drawn by hand), Diabetes' Blood Sugar moodle, the
sun block item, the MS pill bottles, the clotting powder, the pill caddy and the insulin magazine. Each is a 16 x 16 grid of
palette letters, written out at 32 x 32 as a PNG (no libraries needed). Also the
age trait icons (TRAIT_ICONS), written at 18 x 18 into 42/media/ui/Traits; the
other trait icons there were drawn by hand.

    python DanTraits/tools/make_icons.py            write them into the mod
    python DanTraits/tools/make_icons.py --sheet F  also write one sheet of all of them to F

Moodle icons go to 42/media/ui and 42/media/ui/32 (Moodle Framework looks in
the size folder first), the item icon to 42/media/textures.
"""
import os
import struct
import sys
import zlib

HERE = os.path.dirname(os.path.abspath(__file__))
MEDIA = os.path.join(HERE, "..", "42", "media")

PALETTE = {
    ".": (0, 0, 0, 0),
    "k": (30, 30, 30, 255),      # outline
    "w": (250, 250, 250, 255),
    "l": (195, 195, 195, 255),   # light grey
    "d": (95, 95, 95, 255),      # dark grey
    "r": (205, 45, 45, 255),
    "R": (130, 20, 20, 255),     # dark red
    "o": (240, 140, 40, 255),
    "y": (250, 210, 60, 255),
    "b": (60, 120, 220, 255),
    "c": (130, 210, 235, 255),   # pale blue
    "g": (75, 170, 85, 255),
    "n": (130, 90, 50, 255),     # brown
    "N": (85, 55, 30, 255),      # dark brown
    "s": (235, 190, 150, 255),   # skin
    "p": (240, 135, 155, 255),   # pink
    "v": (150, 90, 190, 255),    # purple
}

ICONS = {
    # a capsule over an upward arrow (antidepressants taken: the regimen running)
    "ui/Antidepressants": """
................
...kkkkkkkkk....
..kbbbbbkwwwk...
.kbbbbbbkwwwwk..
.kbbbbbbkwwwwk..
..kbbbbbkwwwk...
...kkkkkkkkk....
................
.......kk.......
......kggk......
.....kggggk.....
....kggggggk....
...kkkkggkkkk...
......kggk......
......kggk......
......kkkk......
""",
    # a capsule over a heavy downward arrow (the day after sumatriptan: heavy-limbed and clumsy)
    "ui/TriptanAfter": """
................
...kkkkkkkkk....
..kvvvvvkwwwk...
.kvvvvvvkwwwwk..
.kvvvvvvkwwwwk..
..kvvvvvkwwwk...
...kkkkkkkkk....
................
......kkkk......
......kddk......
......kddk......
...kkkkddkkkk...
....kddddddk....
.....kddddk.....
......kddk......
.......kk.......
""",    # a glaring sun over a screwed-shut eye (Migraines: the light making an attack worse)
    "ui/LightTooBright": """
.......yy.......
..y....yy....y..
...y..kkkk..y...
.....kyyyyk.....
....kyywwyyk....
yy..kywwyyyk..yy
yy..kyyyyyok..yy
....kyyyyook....
.....kyoook.....
...y..kkkk..y...
..y....yy....y..
.......yy.......
................
..kk........kk..
....kkkkkkkk....
.....k.k..k.k...
""",
    # a drop of blood beside a sugar cube (Diabetes feeds this one itself)
    "ui/BloodSugar": """
................
....k...........
...krk..........
...krk..........
..krrrk.........
..krrrk.........
.krrrrrk........
.krwrrrk........
krwrrrrrk.......
krwrrrkkkkkkkk..
krrrrrkwwwwwwlk.
.krrrrkwwwlwwlk.
..kkkkkwlwwwwlk.
......kwwwwlwlk.
......klllllllk.
......kkkkkkkkk.
""",
    # a heart with a plaster across it (the week after a heart attack)
    "ui/WeakHeart": """
................
..kkkk...kkkk...
.krrrrk.krrrrk..
krrrrrrkrrrrrrk.
krrrrrrrrrrrrrk.
krrkkkkkkkkkrrk.
krrkllllllllkrk.
krrkllkllkllkrk.
.krkllllllllkk..
.krrkkkkkkkkrk..
..krrrrrrrrrk...
...krrrrrrrk....
....krrrrrk.....
.....krrrk......
......krk.......
.......k........
""",
    # a heart with a crack through it
    "ui/ChestPain": """
................
..kkkk...kkkk...
.krrrrk.krrrrk..
krrwrrrkrrkrrrk.
krwrrrrrrkkrrrk.
krrrrrrrkkrrrrk.
krrrrrrkkkkrrrk.
krrrrrrrrkkrrrk.
.krrrrrrkkrrrk..
.krrrrrkkrrrrk..
..krrrrrkrrrk...
...krrrrrrrk....
....krrrrrk.....
.....krrrk......
......krk.......
.......k........
""",
    # a head with a bolt through it
    "ui/Seizure": """
................
....kkkkkkk.....
...kssssssskyk..
..ksssssssskyyk.
..kssssssskyyk..
.kssssssskyyk...
.kssksskkyyykkk.
.ksssskyyyyyyyk.
.ksssskkkkyyykk.
..kssssskyyyk...
..ksssskyyykk...
...ksskyykssk...
...kskyyksssk...
....kyykkkkk....
....kyk.........
....kk..........
""",
    # an ear and the ringing
    "ui/Tinnitus": """
................
...kkkkk........
..ksssssk...k...
.ksskkkssk...k..
.kskssskssk.k.k.
.kskssskssk.k.k.
.ksksskksk..k.k.
.ksskskssk.k..k.
..ksskssk..k.k..
..ksskssk...k...
...kskssk.......
...kssssk..y.y..
....ksssk...y...
....kkkkk..y.y..
................
................
""",
    # a stomach in knots
    "ui/GutFlare": """
................
.....kk.........
....kppk........
....kppk.kkkk...
....kppkkppppk..
....kpppppppppk.
...kppppprrppppk
..kpppprrpprrppk
..kppprpprrpprpk
..kppprrpprrpppk
..kpppprrpprppk.
...kpppppppppk..
....kkpppppkk...
......kkppk.....
........kppk....
.........kk.....
""",
    # grime: mud and spatter
    "ui/Filthy": """
................
......kk........
.....knnk....k..
.....knnk...knk.
....knnnnk...k..
....knNnnk......
...knnnnnnk.....
...knnNnnnk..k..
...knnnnNnk.knk.
....knnnnk..knk.
.k...kkkk....k..
knk.............
knk..kkkkkkkk...
.k..knnNnnnnnk..
....knnnnNnnnk..
.....kkkkkkkk...
""",
    # the sun, burning
    "ui/Sunburn": """
.......y........
.......y........
..y....y....y...
...y.kkkkk.y....
....kyyyyyk.....
...kyyoooyyk....
...kyoorooyk....
yyykyorrroykyyy.
...kyoorooyk....
...kyyoooyyk....
....kyyyyyk.....
...y.kkkkk.y....
..y....y....y...
.......y........
.......y........
................
""",
    # a drop, nearly empty
    "ui/Dehydration": """
................
.......k........
......kwk.......
......kwk.......
.....kwwwk......
.....kwwwk......
....kwwwwwk.....
....kwwwwwk.....
...kwwwwwwwk....
...kwwwwwwwk....
..kwwwwwwwwwk...
..kwwwwwwwwwk...
..kbbbwwwwwbk...
..kbbbbbbbbbk...
...kbbbbbbbk....
....kkkkkkk.....
""",
    # an empty mug
    "ui/CaffeineWithdrawal": """
................
................
....d...d.......
.....d...d......
....d...d.......
................
.kkkkkkkkkkk....
.kwwwwwwwwwkkkk.
.kwwwwwwwwwk..k.
.kwwwwwwwwwk..k.
.kwwwwwwwwwk..k.
.kwwwwwwwwwkkkk.
.kwnnnnnnnwk....
..kwwwwwwwk.....
...kkkkkkk......
................
""",
    # a bottle, and the shakes
    "ui/AlcoholWithdrawal": """
................
......kkk.......
......knk.......
......kgk.......
..k...kgk...k...
.k...kgggk...k..
..k.kgggggk.k...
.k..kgggggk..k..
..k.kgwwwgk.k...
....kgwwwgk.....
..k.kgwwwgk.k...
.k..kgggggk..k..
..k.kgggggk.k...
....kgggggk.....
....kkkkkkk.....
................
""",
    # a cigarette
    "ui/NicotineCraving": """
................
...........d....
..........d.....
...........d....
..........d.....
...........d....
................
kkkkkkkkkkkkkkk.
koookwwwwwwwwrk.
koookwwwwwwwwrk.
kkkkkkkkkkkkkkk.
................
................
................
................
................
""",
    # a cloud that rains
    "ui/Depression": """
................
................
.....kkkk.......
....kddddk.kk...
...kddddddkddk..
..kkddddddddddk.
.kddddddddddddk.
kddddddddddddddk
kddddddddddddddk
.kkkkkkkkkkkkkk.
................
..b...b...b.....
.b...b...b...b..
....b...b...b...
...b...b...b....
................
""",
    # a pale drop of blood
    "ui/LowIron": """
................
.......k........
......krk.......
......krk.......
.....krrrk......
.....kpprk......
....kpppprk.....
....kwppprk.....
...kwwpppprk....
...kwwppppprk...
..kwwwppppprk...
..kwwppppprrk...
..kpppppprrrk...
..kppppprrrrk...
...kpprrrrrk....
....kkkkkkk.....
""",
    # a joint, sore
    "ui/StiffJoints": """
................
.kk.kk..........
kwwkwwk.........
kwwwwwk.........
.kwwwwk.........
..kwwwwk........
...kwwwwk.......
....kwwrrk......
.....krrrrk.....
......krrwwk....
.......kwwwwk...
........kwwwwk..
.........kwwwwk.
.........kwwwwwk
.........kwwkwwk
..........kk.kk.
""",
    # MS: a thermometer running hot, heat rising off it
    "ui/MSHeat": """
................
......kkk....o..
.....kwwwk..o...
.....kwrwk...o..
.....kwrwk..o...
.....kwrwk......
.....kwrwk..o...
.....kwrwk...o..
.....kwrwk..o...
.....kwrwk...o..
....kwrrrwk.....
...kwrrrrrwk....
...krrrrrrrk....
...krrrrrrrk....
....krrrrrk.....
.....kkkkk......
""",
    # MS: a flare, a bolt through a nerve
    "ui/MSFlare": """
................
.....kkkkkk.....
...kkvvvvvvkk...
..kvvvvvkkvvvk..
..kvvvvkyykvvk..
.kvvvvkyykvvvvk.
.kvvvkyykkkkvvk.
.kvvkyyyyyykvvk.
.kvvkkkkyykvvvk.
.kvvvvvkyykvvvk.
..kvvvkyykvvvk..
..kvvvkykvvvvk..
...kkvkkvvvkk...
.....kkkkkk.....
................
................
""",
    # MS pill bottle: prednisone (steroid), a coloured label
    # nitroglycerin: a small amber bottle with a red heart on the label
    "textures/Item_Nitroglycerin": """
................
................
......kkkk......
......kwwk......
.....kkkkkk.....
....kooooook....
....kooooook....
....kowwwwok....
....kowrwrok....
....kowrrrok....
....kowwrwok....
....kowwwwok....
....koooooook...
....kRooooRk....
.....kkkkkk.....
................
""",
    "textures/Item_Prednisone": """
................
.....kkkkkk.....
....kwwwwwwk....
....kwwwwwwk....
....kkkkkkkk....
...kooooooook...
...kooooooook...
...kwwwwwwwwk...
...kwrrrrrrwk...
...kwwwwwwwwk...
...kwrrrrrrwk...
...kwwwwwwwwk...
...kooooooook...
...kooooooook...
...kkkkkkkkkk...
................
""",
    # MS pill bottle: baclofen (muscle relaxant), a coloured label
    "textures/Item_Baclofen": """
................
.....kkkkkk.....
....kwwwwwwk....
....kwwwwwwk....
....kkkkkkkk....
...kooooooook...
...kooooooook...
...kwwwwwwwwk...
...kwbbbbbbwk...
...kwwwwwwwwk...
...kwbbbbbbwk...
...kwwwwwwwwk...
...kooooooook...
...kooooooook...
...kkkkkkkkkk...
................
""",
    # MS pill bottle: amantadine (for fatigue), a coloured label
    "textures/Item_Amantadine": """
................
.....kkkkkk.....
....kwwwwwwk....
....kwwwwwwk....
....kkkkkkkk....
...kooooooook...
...kooooooook...
...kwwwwwwwwk...
...kwggggggwk...
...kwwwwwwwwk...
...kwggggggwk...
...kwwwwwwwwk...
...kooooooook...
...kooooooook...
...kkkkkkkkkk...
................
""",
    # a tube of sun block
    "textures/Item_Sunblock": """
................
.....kkkkkk.....
.....kwwwwk.....
.....kwwwwk.....
....kkkkkkkk....
....koooooook...
...kooooooook...
...koooyyoook...
...kooyyyyook...
...kooyyyyook...
...koooyyoook...
...kooooooook...
...kwwwwwwwwk...
...kooooooook...
...kkkkkkkkkk...
................
""",
    # clotting powder: a shaker tin, holes in the lid, a drop of blood on the label
    "textures/Item_ClottingPowder": """
................
.....kkkkkk.....
....kldldldk....
....kllllllk....
....kkkkkkkk....
...kbbbbbbbbk...
...kwwwwwwwwk...
...kwwwrwwwwk...
...kwwrrrwwwk...
...kwrrrrrwwk...
...kwrrrrrwwk...
...kwwrrrwwwk...
...kwwwwwwwwk...
...kbbbbbbbbk...
...kkkkkkkkkk...
................
""",
    # Living With Type 1: a magazine, a blue masthead over a drop of blood
    "textures/Item_InsulinMag": """
................
..kkkkkkkkkkk...
..kbbbbbbbbbkk..
..kbwbwwbwbbkdk.
..kbbbbbbbbbkdk.
..kwwwwwwwwwkdk.
..kwwwwkwwwwkdk.
..kwwwkrkwwwkdk.
..kwwkrrrkwwkdk.
..kwkrrrrrkwkdk.
..kwkrwrrrkwkdk.
..kwwkrrrkwwkdk.
..kwwwkkkwwwkdk.
..kwldldldlwkdk.
..kkkkkkkkkkkdk.
...kkkkkkkkkkk..
""",
    # pill caddy: a weekly organiser, seven coloured lids over the
    # compartments, a few pills showing (placeholder until it has real art)
    "textures/Item_PillCaddy": """
................
................
................
................
kkkkkkkkkkkkkkk.
kbkrkykgkckvkpk.
kbkrkykgkckvkpk.
kbkrkykgkckvkpk.
kkkkkkkkkkkkkkk.
kwlwlwlwlwlwlwk.
kwlolwlplwlylwk.
kwlwlwlwlwlwlwk.
kkkkkkkkkkkkkkk.
................
................
................
""",
}


# Trait icons: 18 x 18 at 1x like the vanilla ones, written to
# 42/media/ui/Traits/trait_<key>.png (the game finds them by the trait's key).
# The art may be any size up to 18 x 18; it is centred on its drawn pixels.
TRAIT_SIZE = 18

# The four Age traits are a disc in the band's colour with the decade on it.
DIGITS = {
    "0": [".ww.", "w..w", "w..w", "w..w", "w..w", "w..w", ".ww."],
    "2": [".ww.", "w..w", "...w", "..w.", ".w..", "w...", "wwww"],
    "3": ["www.", "...w", "...w", ".ww.", "...w", "...w", "www."],
    "4": ["w..w", "w..w", "w..w", "wwww", "...w", "...w", "...w"],
    "5": ["wwww", "w...", "w...", "www.", "...w", "...w", "www."],
}
AGE_BADGES = {"age20s": ("20", "g"), "age30s": ("30", "b"), "age40s": ("40", "o"), "age50s": ("50", "d")}


def age_badge(text, fill):
    n = 16
    grid = [["."] * n for _ in range(n)]
    c = (n - 1) / 2.0
    for y in range(n):
        for x in range(n):
            d = ((x - c) ** 2 + (y - c) ** 2) ** 0.5
            if d <= 7.6:
                grid[y][x] = "k" if d > 6.6 else fill
    x0, y0 = 3, 4
    for i, ch in enumerate(text):
        for dy, row in enumerate(DIGITS[ch]):
            for dx, p in enumerate(row):
                if p == "w":
                    grid[y0 + dy][x0 + i * 6 + dx] = "w"
    return "\n".join("".join(r) for r in grid)


TRAIT_ICONS = {
    # Green: a sprout in a pot
    "green": """
..kkk......kkk..
.kgggk....kgggk.
.kggggk..kggggk.
..kgggkkkkgggk..
...kkggkkggkk...
.....kkggkk.....
.......gk.......
.......gk.......
.......gk.......
...kkkkkkkkkk...
...knnnnnnnnk...
....knNnnNnk....
....knnnnnnk....
.....kkkkkk.....
""",
    # Quick Study: a light bulb
    "quickstudy": """
y.....kkkk.....y
.y...kyyyyk...y.
....kywwyyyk....
...kywwyyyyyk...
...kywyyyyyyk...
...kyyyyyyyyk...
yy.kyyyyyyyyk.yy
....kyyyyyyk....
.....kyyyyk.....
.....kllllk.....
.....kddddk.....
.....kllllk.....
......kkkk......
""",
    # Reading Glasses: a pair of round lenses
    "readingglasses": """
k..............k
k..............k
.kkkkkk..kkkkkk.
kkwccckkkkwccckk
kkcwcck..kcwcckk
.kcccck..kcccck.
.kcccck..kcccck.
..kkkk....kkkk..
""",
    # Bad Back: a spine, the lowest vertebrae red and hurting
    "badback": """
.....kkkkkk.....
...kkwwwwwwkk...
.....kkkkkk.....
.....kllllk.....
.....kkkkkk.....
...kkwwwwwwkk...
.....kkkkkk.....
.....kllllk.....
.....kkkkkk.....
...kkrrrrrrkk...
.r...kkkkkk...r.
..r..krrrrk..r..
.r...kkkkkk...r.
...kkrrrrrrkk...
.....kkkkkk.....
""",
    # Bad Knees: a leg with a sore red knee
    "badknees": """
....kkkk....
....kssk....
....kssk....
....kssk....
....kssk....
.r.krrrrk.r.
r..krrrrk..r
.r.krrrrk.r.
....kssk....
....kssk....
....kssk....
....kssk....
....ksskkkk.
....knnnnnnk
....kkkkkkkk
""",
    # Old Hand: a well-used hammer
    "oldhand": """
.kkkkkkkkkk.
kllllllllddk
kddddddddddk
.kkkknnkkkk.
....knnk....
....knnk....
....knNk....
....knnk....
....knNk....
....knnk....
....knnk....
....kkkk....
""",
    # Old Injury: a bone with an old bandage round it
    "oldinjury": """
.kk....kkk....kk.
kwwk...klk...kwwk
kwwwkkkklkkkkwwwk
.kwwwwwkrkwwwwwk.
kwwwkkkklkkkkwwwk
kwwk...klk...kwwk
.kk....kkk....kk.
""",
    # Set in Their Ways: a favourite armchair
    "setinways": """
..kkkkkkkkkk..
..knnnnnnnnk..
..knNnnnnNnk..
..knnnnnnnnk..
kkknnnnnnnnkkk
knnknnnnnnknnk
knnkkkkkkkknnk
knnkNNNNNNknnk
knnkkkkkkkknnk
knnnnnnnnnnnnk
kkkkkkkkkkkkkk
.kk........kk.
""",
    # Bounces Back: a ball on the rebound
    "bouncesback": """
..........kkkk..
.........krrrrk.
........krwrrrrk
........krrrrrrk
........krrrrrrk
.........krrrrk.
.......d..kkkk..
................
.....d..........
................
...d............
................
.d..............
kkkkkkkkkkkkkkkk
""",
    # Grit: a clenched fist
    "grit": """
...kkkkkkkkk..
..ksskssksskk.
.kssksskssksk.
.kssksskssksk.
.kssksskssksk.
kkkkkkkkkkkssk
ksssssssskssk.
.kkkkkkkkksssk
..kssssssssssk
..kssssssssssk
...kssssssssk.
...kssssssssk.
....kkkkkkkk..
""",
    # Bottomless Pit: a drumstick, half gone
    "bottomlesspit": """
....kkkk......
..kknnnnkk....
.knnnnnnnnk...
knnNnnnnnnnk..
knnnnnnnnnnk..
knnnnnnNnnnk..
.knnnnnnnnk...
..knnnnnnk....
...kknnnkk....
.....kwwk.....
......kwwk....
.......kwwkk..
......kwwwwwk.
......kwkkwwk.
.......k..kk..
""",
    # Seen It All: an unimpressed eye under a grey brow
    "seenitall": """
...llllllllll...
..l..........l..
....kkkkkkkk....
..kksssssssskk..
.kssssssssssssk.
kkkkkkkkkkkkkkkk
kwwwwkbkkbkwwwwk
.kwwwkbbbbkwwwk.
..kkwwkkkkwwkk..
....kkkkkkkk....
""",
    # Pace Yourself: an hourglass, half run
    "paceyourself": """
kkkkkkkkk
knnnnnnnk
.kccccck.
.kyyyyyk.
..kyyyk..
...kyk...
...kyk...
..kcyck..
.kccycck.
.kcyyyck.
.kyyyyyk.
knnnnnnnk
kkkkkkkkk
""",
    # Settled: a house
    "settled": """
.......kk.......
......krrk......
.....krrrrk.....
....krrrrrrk....
...krrrrrrrrk...
..krrrrrrrrrrk..
.kkkkkkkkkkkkkk.
..kllllllllllk..
..klkkkllkkklk..
..klkckllknklk..
..klkkkllknklk..
..kllllllknklk..
..kllllllknklk..
kkkkkkkkkkkkkkkk
""",
    # Old Bones Know Rain: a storm cloud over a bone
    "oldbones": """
....kkkk........
...kddddk.kk....
..kddddddkddk...
.kkddddddddddk..
kddddddddddddk..
.kkkkkkkkkkkk...
..b..y...b......
.b..yy..b.......
...yy...........
...y............
................
.kk.........kk..
kwwkkkkkkkkkwwk.
.kwwwwwwwwwwwk..
kwwkkkkkkkkkwwk.
.kk.........kk..
""",
    # Cast Iron: a cast-iron frying pan
    "castiron": """
...kkkk.........
.kkddddkk.......
.kdlldddk.......
kdlddddddk......
kddddddddkkkkkk.
kddddddddddddddk
kddddddddkkkkkk.
.kddddddk.......
.kkddddkk.......
...kkkk.........
""",
    # Delicate Stomach: a stomach gone green and queasy
    "delicatestomach": """
.....kk.........
....kppk........
....kppk.kkkk...
....kppkkppppk..
....kpppppppppk.
...kppppppppppk.
..kppppggppppk..
..kpppgppgpppk..
..kppgppppgppk..
..kpppppggpppk..
..kppppppppppk..
...kpppppppppk..
....kkpppppkk...
......kkppk.....
........kppk....
.........kk.....
""",
}
for _key, (_text, _fill) in AGE_BADGES.items():
    TRAIT_ICONS[_key] = age_badge(_text, _fill)


def rows_of(art):
    rows = [r for r in art.strip("\n").split("\n")]
    if len(rows) != 16:
        raise ValueError("expected 16 rows, got %d" % len(rows))
    out = []
    for r in rows:
        r = (r + "." * 16)[:16]
        out.append([PALETTE[ch] for ch in r])
    return out


def trait_rows(name, art):
    """The art centred on its drawn pixels in an 18 x 18 grid."""
    rows = art.strip("\n").split("\n")
    width = max(len(r) for r in rows)
    if width > TRAIT_SIZE or len(rows) > TRAIT_SIZE:
        raise ValueError("%s: art is %d x %d, at most %d" % (name, width, len(rows), TRAIT_SIZE))
    if any(len(r) != width for r in rows):
        raise ValueError("%s: rows of different widths" % name)
    drawn = [(x, y) for y, r in enumerate(rows) for x, ch in enumerate(r) if ch != "."]
    x0, x1 = min(x for x, _ in drawn), max(x for x, _ in drawn)
    y0, y1 = min(y for _, y in drawn), max(y for _, y in drawn)
    ox = (TRAIT_SIZE - (x1 - x0 + 1)) // 2 - x0
    oy = (TRAIT_SIZE - (y1 - y0 + 1)) // 2 - y0
    out = [[PALETTE["."]] * TRAIT_SIZE for _ in range(TRAIT_SIZE)]
    for x, y in drawn:
        out[y + oy][x + ox] = PALETTE[rows[y][x]]
    return out


def png(pixels):
    """pixels: rows of (r, g, b, a)."""
    height, width = len(pixels), len(pixels[0])
    raw = b"".join(b"\x00" + b"".join(struct.pack("BBBB", *p) for p in row) for row in pixels)

    def chunk(kind, data):
        body = kind + data
        return struct.pack(">I", len(data)) + body + struct.pack(">I", zlib.crc32(body) & 0xFFFFFFFF)

    return (b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0))
            + chunk(b"IDAT", zlib.compress(raw, 9)) + chunk(b"IEND", b""))


def scaled(rows, k):
    out = []
    for row in rows:
        wide = [p for p in row for _ in range(k)]
        out.extend([wide] * k)
    return out


def main(argv):
    written = []
    for name, art in ICONS.items():
        data = png(scaled(rows_of(art), 2))
        targets = [os.path.join(MEDIA, name + ".png")]
        if name.startswith("ui/"):
            targets.append(os.path.join(MEDIA, "ui", "32", name[3:] + ".png"))
        for path in targets:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "wb") as f:
                f.write(data)
            written.append(path)
    for key, art in TRAIT_ICONS.items():
        path = os.path.join(MEDIA, "ui", "Traits", "trait_%s.png" % key)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "wb") as f:
            f.write(png(trait_rows(key, art)))
        written.append(path)
    print("wrote %d files" % len(written))
    if "--sheet" in argv:
        if argv.index("--sheet") + 1 >= len(argv):
            raise SystemExit("usage: make_icons.py [--sheet <out.png>]")
        path = argv[argv.index("--sheet") + 1]
        grids = [rows_of(art) for art in ICONS.values()]
        grids += [trait_rows(key, art) for key, art in TRAIT_ICONS.items()]
        cols, k, pad = 7, 6, 8
        cell = TRAIT_SIZE * k + pad
        lines = (len(grids) + cols - 1) // cols
        bg = (120, 120, 120, 255)
        sheet = [[bg] * (cols * cell + pad) for _ in range(lines * cell + pad)]
        for i, grid in enumerate(grids):
            big = scaled(grid, k)
            x0, y0 = pad + (i % cols) * cell, pad + (i // cols) * cell
            for y, row in enumerate(big):
                for x, p in enumerate(row):
                    if p[3]:
                        sheet[y0 + y][x0 + x] = p
        with open(path, "wb") as f:
            f.write(png(sheet))
        print("sheet:", path)


if __name__ == "__main__":
    main(sys.argv[1:])
