"""Draw the mod's simple pixel icons: the moodles fed by DanTraits_Moodles.lua
(all but Spoons, whose art was drawn by hand), Diabetes' Blood Sugar moodle, the
sun block item, the MS pill bottles and the pill caddy. Each is a 16 x 16 grid of
palette letters, written out at 32 x 32 as a PNG (no libraries needed).

    python DanTraits/tools/make_icons.py            write them into the mod
    python DanTraits/tools/make_icons.py --sheet F  also write one sheet of all of them to F

Moodle icons go to 42/media/ui and 42/media/ui/32 (Moodle Framework looks in
the size folder first), the item icon to 42/media/textures.
"""
import os
import struct
import sys
import zlib

HERE = os.path.dirname(os.path.abspath(__file__))
MEDIA = os.path.join(HERE, "..", "42", "media")

PALETTE = {
    ".": (0, 0, 0, 0),
    "k": (30, 30, 30, 255),      # outline
    "w": (250, 250, 250, 255),
    "l": (195, 195, 195, 255),   # light grey
    "d": (95, 95, 95, 255),      # dark grey
    "r": (205, 45, 45, 255),
    "R": (130, 20, 20, 255),     # dark red
    "o": (240, 140, 40, 255),
    "y": (250, 210, 60, 255),
    "b": (60, 120, 220, 255),
    "c": (130, 210, 235, 255),   # pale blue
    "g": (75, 170, 85, 255),
    "n": (130, 90, 50, 255),     # brown
    "N": (85, 55, 30, 255),      # dark brown
    "s": (235, 190, 150, 255),   # skin
    "p": (240, 135, 155, 255),   # pink
    "v": (150, 90, 190, 255),    # purple
}

ICONS = {
    # a drop of blood beside a sugar cube (Diabetes feeds this one itself)
    "ui/BloodSugar": """
................
....k...........
...krk..........
...krk..........
..krrrk.........
..krrrk.........
.krrrrrk........
.krwrrrk........
krwrrrrrk.......
krwrrrkkkkkkkk..
krrrrrkwwwwwwlk.
.krrrrkwwwlwwlk.
..kkkkkwlwwwwlk.
......kwwwwlwlk.
......klllllllk.
......kkkkkkkkk.
""",
    # a heart with a crack through it
    "ui/ChestPain": """
................
..kkkk...kkkk...
.krrrrk.krrrrk..
krrwrrrkrrkrrrk.
krwrrrrrrkkrrrk.
krrrrrrrkkrrrrk.
krrrrrrkkkkrrrk.
krrrrrrrrkkrrrk.
.krrrrrrkkrrrk..
.krrrrrkkrrrrk..
..krrrrrkrrrk...
...krrrrrrrk....
....krrrrrk.....
.....krrrk......
......krk.......
.......k........
""",
    # a head with a bolt through it
    "ui/Seizure": """
................
....kkkkkkk.....
...kssssssskyk..
..ksssssssskyyk.
..kssssssskyyk..
.kssssssskyyk...
.kssksskkyyykkk.
.ksssskyyyyyyyk.
.ksssskkkkyyykk.
..kssssskyyyk...
..ksssskyyykk...
...ksskyykssk...
...kskyyksssk...
....kyykkkkk....
....kyk.........
....kk..........
""",
    # an ear and the ringing
    "ui/Tinnitus": """
................
...kkkkk........
..ksssssk...k...
.ksskkkssk...k..
.kskssskssk.k.k.
.kskssskssk.k.k.
.ksksskksk..k.k.
.ksskskssk.k..k.
..ksskssk..k.k..
..ksskssk...k...
...kskssk.......
...kssssk..y.y..
....ksssk...y...
....kkkkk..y.y..
................
................
""",
    # a stomach in knots
    "ui/GutFlare": """
................
.....kk.........
....kppk........
....kppk.kkkk...
....kppkkppppk..
....kpppppppppk.
...kppppprrppppk
..kpppprrpprrppk
..kppprpprrpprpk
..kppprrpprrpppk
..kpppprrpprppk.
...kpppppppppk..
....kkpppppkk...
......kkppk.....
........kppk....
.........kk.....
""",
    # grime: mud and spatter
    "ui/Filthy": """
................
......kk........
.....knnk....k..
.....knnk...knk.
....knnnnk...k..
....knNnnk......
...knnnnnnk.....
...knnNnnnk..k..
...knnnnNnk.knk.
....knnnnk..knk.
.k...kkkk....k..
knk.............
knk..kkkkkkkk...
.k..knnNnnnnnk..
....knnnnNnnnk..
.....kkkkkkkk...
""",
    # the sun, burning
    "ui/Sunburn": """
.......y........
.......y........
..y....y....y...
...y.kkkkk.y....
....kyyyyyk.....
...kyyoooyyk....
...kyoorooyk....
yyykyorrroykyyy.
...kyoorooyk....
...kyyoooyyk....
....kyyyyyk.....
...y.kkkkk.y....
..y....y....y...
.......y........
.......y........
................
""",
    # a drop, nearly empty
    "ui/Dehydration": """
................
.......k........
......kwk.......
......kwk.......
.....kwwwk......
.....kwwwk......
....kwwwwwk.....
....kwwwwwk.....
...kwwwwwwwk....
...kwwwwwwwk....
..kwwwwwwwwwk...
..kwwwwwwwwwk...
..kbbbwwwwwbk...
..kbbbbbbbbbk...
...kbbbbbbbk....
....kkkkkkk.....
""",
    # an empty mug
    "ui/CaffeineWithdrawal": """
................
................
....d...d.......
.....d...d......
....d...d.......
................
.kkkkkkkkkkk....
.kwwwwwwwwwkkkk.
.kwwwwwwwwwk..k.
.kwwwwwwwwwk..k.
.kwwwwwwwwwk..k.
.kwwwwwwwwwkkkk.
.kwnnnnnnnwk....
..kwwwwwwwk.....
...kkkkkkk......
................
""",
    # a bottle, and the shakes
    "ui/AlcoholWithdrawal": """
................
......kkk.......
......knk.......
......kgk.......
..k...kgk...k...
.k...kgggk...k..
..k.kgggggk.k...
.k..kgggggk..k..
..k.kgwwwgk.k...
....kgwwwgk.....
..k.kgwwwgk.k...
.k..kgggggk..k..
..k.kgggggk.k...
....kgggggk.....
....kkkkkkk.....
................
""",
    # a cigarette
    "ui/NicotineCraving": """
................
...........d....
..........d.....
...........d....
..........d.....
...........d....
................
kkkkkkkkkkkkkkk.
koookwwwwwwwwrk.
koookwwwwwwwwrk.
kkkkkkkkkkkkkkk.
................
................
................
................
................
""",
    # a cloud that rains
    "ui/Depression": """
................
................
.....kkkk.......
....kddddk.kk...
...kddddddkddk..
..kkddddddddddk.
.kddddddddddddk.
kddddddddddddddk
kddddddddddddddk
.kkkkkkkkkkkkkk.
................
..b...b...b.....
.b...b...b...b..
....b...b...b...
...b...b...b....
................
""",
    # a pale drop of blood
    "ui/LowIron": """
................
.......k........
......krk.......
......krk.......
.....krrrk......
.....kpprk......
....kpppprk.....
....kwppprk.....
...kwwpppprk....
...kwwppppprk...
..kwwwppppprk...
..kwwppppprrk...
..kpppppprrrk...
..kppppprrrrk...
...kpprrrrrk....
....kkkkkkk.....
""",
    # a joint, sore
    "ui/StiffJoints": """
................
.kk.kk..........
kwwkwwk.........
kwwwwwk.........
.kwwwwk.........
..kwwwwk........
...kwwwwk.......
....kwwrrk......
.....krrrrk.....
......krrwwk....
.......kwwwwk...
........kwwwwk..
.........kwwwwk.
.........kwwwwwk
.........kwwkwwk
..........kk.kk.
""",
    # MS: a thermometer running hot, heat rising off it
    "ui/MSHeat": """
................
......kkk....o..
.....kwwwk..o...
.....kwrwk...o..
.....kwrwk..o...
.....kwrwk......
.....kwrwk..o...
.....kwrwk...o..
.....kwrwk..o...
.....kwrwk...o..
....kwrrrwk.....
...kwrrrrrwk....
...krrrrrrrk....
...krrrrrrrk....
....krrrrrk.....
.....kkkkk......
""",
    # MS: a flare, a bolt through a nerve
    "ui/MSFlare": """
................
.....kkkkkk.....
...kkvvvvvvkk...
..kvvvvvkkvvvk..
..kvvvvkyykvvk..
.kvvvvkyykvvvvk.
.kvvvkyykkkkvvk.
.kvvkyyyyyykvvk.
.kvvkkkkyykvvvk.
.kvvvvvkyykvvvk.
..kvvvkyykvvvk..
..kvvvkykvvvvk..
...kkvkkvvvkk...
.....kkkkkk.....
................
................
""",
    # MS pill bottle: prednisone (steroid), a coloured label
    "textures/Item_Prednisone": """
................
.....kkkkkk.....
....kwwwwwwk....
....kwwwwwwk....
....kkkkkkkk....
...kooooooook...
...kooooooook...
...kwwwwwwwwk...
...kwrrrrrrwk...
...kwwwwwwwwk...
...kwrrrrrrwk...
...kwwwwwwwwk...
...kooooooook...
...kooooooook...
...kkkkkkkkkk...
................
""",
    # MS pill bottle: baclofen (muscle relaxant), a coloured label
    "textures/Item_Baclofen": """
................
.....kkkkkk.....
....kwwwwwwk....
....kwwwwwwk....
....kkkkkkkk....
...kooooooook...
...kooooooook...
...kwwwwwwwwk...
...kwbbbbbbwk...
...kwwwwwwwwk...
...kwbbbbbbwk...
...kwwwwwwwwk...
...kooooooook...
...kooooooook...
...kkkkkkkkkk...
................
""",
    # MS pill bottle: amantadine (for fatigue), a coloured label
    "textures/Item_Amantadine": """
................
.....kkkkkk.....
....kwwwwwwk....
....kwwwwwwk....
....kkkkkkkk....
...kooooooook...
...kooooooook...
...kwwwwwwwwk...
...kwggggggwk...
...kwwwwwwwwk...
...kwggggggwk...
...kwwwwwwwwk...
...kooooooook...
...kooooooook...
...kkkkkkkkkk...
................
""",
    # a tube of sun block
    "textures/Item_Sunblock": """
................
.....kkkkkk.....
.....kwwwwk.....
.....kwwwwk.....
....kkkkkkkk....
....koooooook...
...kooooooook...
...koooyyoook...
...kooyyyyook...
...kooyyyyook...
...koooyyoook...
...kooooooook...
...kwwwwwwwwk...
...kooooooook...
...kkkkkkkkkk...
................
""",
    # pill caddy: a weekly organiser, seven coloured lids over the
    # compartments, a few pills showing (placeholder until it has real art)
    "textures/Item_PillCaddy": """
................
................
................
................
kkkkkkkkkkkkkkk.
kbkrkykgkckvkpk.
kbkrkykgkckvkpk.
kbkrkykgkckvkpk.
kkkkkkkkkkkkkkk.
kwlwlwlwlwlwlwk.
kwlolwlplwlylwk.
kwlwlwlwlwlwlwk.
kkkkkkkkkkkkkkk.
................
................
................
""",
}


def rows_of(art):
    rows = [r for r in art.strip("\n").split("\n")]
    if len(rows) != 16:
        raise ValueError("expected 16 rows, got %d" % len(rows))
    out = []
    for r in rows:
        r = (r + "." * 16)[:16]
        out.append([PALETTE[ch] for ch in r])
    return out


def png(pixels):
    """pixels: rows of (r, g, b, a)."""
    height, width = len(pixels), len(pixels[0])
    raw = b"".join(b"\x00" + b"".join(struct.pack("BBBB", *p) for p in row) for row in pixels)

    def chunk(kind, data):
        body = kind + data
        return struct.pack(">I", len(data)) + body + struct.pack(">I", zlib.crc32(body) & 0xFFFFFFFF)

    return (b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0))
            + chunk(b"IDAT", zlib.compress(raw, 9)) + chunk(b"IEND", b""))


def scaled(rows, k):
    out = []
    for row in rows:
        wide = [p for p in row for _ in range(k)]
        out.extend([wide] * k)
    return out


def main(argv):
    written = []
    for name, art in ICONS.items():
        data = png(scaled(rows_of(art), 2))
        targets = [os.path.join(MEDIA, name + ".png")]
        if name.startswith("ui/"):
            targets.append(os.path.join(MEDIA, "ui", "32", name[3:] + ".png"))
        for path in targets:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "wb") as f:
                f.write(data)
            written.append(path)
    print("wrote %d files" % len(written))
    if "--sheet" in argv:
        if argv.index("--sheet") + 1 >= len(argv):
            raise SystemExit("usage: make_icons.py [--sheet <out.png>]")
        path = argv[argv.index("--sheet") + 1]
        names = list(ICONS)
        cols, k, pad = 7, 6, 8
        cell = 16 * k + pad
        lines = (len(names) + cols - 1) // cols
        bg = (120, 120, 120, 255)
        sheet = [[bg] * (cols * cell + pad) for _ in range(lines * cell + pad)]
        for i, name in enumerate(names):
            big = scaled(rows_of(ICONS[name]), k)
            x0, y0 = pad + (i % cols) * cell, pad + (i // cols) * cell
            for y, row in enumerate(big):
                for x, p in enumerate(row):
                    if p[3]:
                        sheet[y0 + y][x0 + x] = p
        with open(path, "wb") as f:
            f.write(png(sheet))
        print("sheet:", path)


if __name__ == "__main__":
    main(sys.argv[1:])
